name: Github commit action
on: [push]
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Install requirements
        run: pip install -r requirements.txt
      # The next steps should be added by you!
      # - Test the code with flake8
      # - Run the unittests
      # - Build the docker image
      # - Push the docker image to hub.docker.com (you'll need an account there!)